---

-  hosts: 172.25.128.201
   tasks:
   - name: Installation du serveur web nginx
     yum:
      name: epel-release
      state: present
   - name: Installation du serveur web nginx
     yum:
      name: nginx
      state: present
     loop: 
       - httpd
       - php

   - name: Installation du serveur web nginx
     systemd:
      name: nginx
      state: stopped

